name: example
description: Example for flutter_translate_gen

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_translate_annotations:
    git:
      url: git://github.com/f-person/flutter_translate_annotations.git
      ref: master

dev_dependencies:
  build_runner: ">=1.7.0 <2.0.0"
  flutter_translate_gen:
    path: ../
